name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allow manual trigger of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Forked Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/piyushsachdeva/AzureDevOps-Zero-to-Hero.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Sync with Upstream
        run: |
          git checkout main
          git merge upstream/main
          git push origin main
